# Generated by Django 6.0 on 2026-02-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
