# Generated by Django 6.0 on 2026-02-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bookappointment_approved'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookappointment',
            constraint=models.UniqueConstraint(fields=('date',), name='unique_appointment_time'),
        ),
    ]
